name: 'SSH to a runner'
description: 'Allow SSH to a runner'
inputs:
  public-ssh-key:
    description: 'Public SSH key'
    required: true
  wait-minutes:
    description: 'Wait time in minutes'
    required: false
    default: 10
  
runs:
  using: "composite"
  steps:
    - name: Set SSH key
      shell: bash
      run: |
        sudo mkdir /home/runner/.ssh
        echo "${{ inputs.public-ssh-key }}" | sudo tee /home/runner/.ssh/authorized_keys >/dev/null
        sudo chown -R runner:runner /home/runner/.ssh
        sudo chmod 700 /home/runner/.ssh
        sudo chmod 600 /home/runner/.ssh/authorized_keys

    - name: SSH Command
      shell: bash
      run: |
        IPv4=$(curl -sL --ipv4 ifconfig.me)
        echo "User:    runner"
        echo "IPv4:    $IPv4"
        echo "Command: ssh runner@$IPv4"

    - name: Wait for timeout
      shell: bash
      run: sleep $((${{ inputs.wait-minutes }} * 60))