name: 'SSH to a runner'
description: 'Allow SSH to a runner'
inputs:
  public-ssh-key:
    description: 'Public SSH key'
    required: true
  wait-minutes:
    description: 'Wait time in minutes'
    required: false
    default: 3

runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'

branding:
  icon: terminal
  color: orange
