name: 'SSH to a runner'
description: 'Greet someone'
inputs:
  public-ssh-key:
    description: 'Public SSH key'
    # required: true

runs:
  # post: "enable-ssh.sh"
  using: "composite"
  steps:
    - name: Set ssh key
      shell: bash
      run: |
        sudo mkdir /home/runner/.ssh
        echo "${{ inputs.public-ssh-key }}" | sudo tee /home/runner/.ssh/authorized_keys >/dev/null
        sudo chown -R runner:runner /home/runner/.ssh
        sudo chmod 700 /home/runner/.ssh
        sudo chmod 600 /home/runner/.ssh/authorized_keys
    
    - name: Set ssh key
      shell: bash
      run: |
        RANDOM_USERNAME="$(openssl rand -base64 24 | tr '/+' '0A' | tr -d '=')"
        RANDOM_PASSWORD="$(openssl rand -base64 32 | tr '/+' '0A' | tr -d '=')"
        sudo useradd -m "$RANDOM_USERNAME"
        echo "$RANDOM_USERNAME:$RANDOM_PASSWORD" | sudo chpasswd
        echo "Created user: $RANDOM_USERNAME"
        echo "Password: $RANDOM_PASSWORD"
        sudo mkdir -p /home/$RANDOM_USERNAME/.ssh
        sudo chown $RANDOM_USERNAME:$RANDOM_USERNAME /home/$RANDOM_USERNAME/.ssh
        sudo chmod 700 /home/$RANDOM_USERNAME/.ssh
        sudo -u "$RANDOM_USERNAME" bash -c 'echo "exec /bin/su - runner" > ~/.ssh/rc'
        sudo chmod 755 /home/$RANDOM_USERNAME/.ssh/rc
        IPv4=$(curl -sL --ipv4 ifconfig.me)
        echo "command: ssh $RANDOM_USERNAME:$RANDOM_PASSWORD@$IPv4"
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        sudo systemctl restart sshd

    - name: IPv4 SSH Command
      shell: bash
      run: |
        IPv4=$(curl -sL --ipv4 ifconfig.me)
        echo "User: runner"
        echo "IPv4: $IPv4"
        echo "command: ssh runner@$IPv4"

