name: Test this workflow action
on:
  push:

jobs:
  test:
    runs-on: ubicloud
    steps:
      - uses: actions/checkout@v4

      - name: Generate public ssh key
        id: generate-key
        run: | 
          mkdir -p ~/.ssh/
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N "" -q
          PUBLIC_KEY="$(cat ~/.ssh/id_rsa.pub)"
          echo "public_key<<EOF" >> $GITHUB_OUTPUT
          echo "$PUBLIC_KEY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo $PUBLIC_KEY >> ~/.ssh/authorized_keys

      - name: Setup SSH access
        id: ssh
        uses: enescakir/ssh-action@main
        with:
          public-ssh-key: "${{ steps.generate-key.outputs.public_key }}"
          wait-minutes: 1

      - name: Try to ssh
        run: |
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${{ steps.ssh.outputs.user }}@${{ steps.ssh.outputs.ip }} 'uptime'
